{% set name = "qa-analytics-insights" %}
{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0') %}
{% set url = "https://github.com/aydabd/qa-analytics-insights.git" %}
{% set license = "MIT" %}
{% set author = "aydin.a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: {{ url }}
  git_rev: {{ version }}

build:
  number: 0
  noarch: python
  script:
    - python -m pip install --no-deps --ignore-installed .
  entry_points:
    - qa-analytics-insights = qa_analytics_insights.cli:main

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - python >=3.9

test:
  imports:
    - qa_analytics_insights

about:
  home: {{ url }}
  license: {{ license }}
  license_file: LICENSE.txt
  summary: A package/library for analyze and visualize test reports.
  dev_url: https://github.com/aydabd/qa-analytics-insights
  doc_url: https://qa-analytics-insights.readthedocs.io/en/latest/

extra:
  recipe-maintainer:
    - {{ author }}
